# Generated by Django 5.2.7 on 2026-02-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
