# Generated by Django 5.2.7 on 2026-02-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifegoal',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('In Progress', 'In Progress'), ('50% Completed', '50% Completed'), ('70% Completed', '70% Completed'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
