# Generated by Django 5.2.7 on 2026-02-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lifegoal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellshare',
            name='total_sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
