# Generated by Django 5.2.7 on 2026-02-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_futuremessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuremessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='future_messages/images/'),
        ),
        migrations.AddField(
            model_name='futuremessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='future_messages/videos/'),
        ),
    ]
