# Generated by Django 5.2.7 on 2026-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_futuremessage_image_futuremessage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyshare',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
