# Generated by Django 5.2.7 on 2026-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_monthlyparticipation_participationclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationclick',
            name='recorded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
